apiVersion: v1
kind: ReplicationController
metadata:
  name: rancher-ingress-controller
  labels:
    k8s-app: rancher-ingress-lb
spec:
  replicas: 1
  selector:
    k8s-app: rancher-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: rancher-ingress-lb
        name: rancher-ingress-lb
    spec:
      containers:
      - image: rancher/ingress-controller:dev
        name: rancher-ingress-lb
        env:
          - name: CATTLE_URL
            value: "http://10.0.2.2:8080/v1"
          - name: CATTLE_ACCESS_KEY
            value: "15E5B9AB75486D1817C9"
          - name: CATTLE_SECRET_KEY
            value: "uJJh8ivzXqFoS1mcvXqhz7zV2tLLKbw5Ds8bEBR7"
          - name: KUBERNETES_URL
            value: "http://master"
        args:
        - ingress-controller
        - --lb-controller=kubernetes
        - --lb-provider=rancher
