apiVersion: v1
kind: ReplicationController
metadata:
  name: rancher-ingress-controller
  labels:
    k8s-app: rancher-ingress-lb
spec:
  replicas: 1
  selector:
    k8s-app: rancher-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: rancher-ingress-lb
        name: rancher-ingress-lb
    spec:
      containers:
      - image: rancher/rancher-ingress:dev
        name: rancher-ingress-lb
        # use downward API
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: KUBERNETES_SERVER
            value: "http://master:80"
          - name: HAPROXY_CONFIG
            value: "/etc/haproxy/haproxy.cfg"
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        args:
        - rancher-ingress
        - --lb-controller=kubernetes